In [1]:
from nltk.stem import PorterStemmer 
stemmerporter = PorterStemmer() 
stemmerporter.stem('happiness')

'happi'

In [2]:
from nltk.stem import LancasterStemmer 
stemmerporter = LancasterStemmer() 
stemmerporter.stem('happiness')

'happy'

In [3]:
from nltk.stem import RegexpStemmer 
stemmerregexp = RegexpStemmer('ing') 
stemmerregexp.stem('happiness')

'happiness'

In [4]:
from nltk.stem import SnowballStemmer 
SnowballStemmer.languages
frenchStemmer = SnowballStemmer('french') 
frenchStemmer.stem('fille')

'fill'

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine", "optical character recognition is significant"]
vect.fit(corpus)


CountVectorizer(binary=True)

In [6]:
vocab = vect.vocabulary_
for key in sorted(vocab.keys()):
    print("{}:{}".format(key , vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [7]:
print(vect.transform(["This is a good optical illusion. It is a good one"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [8]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(),
                               vect.transform(["OCR is an optical Character Recognition engine"]).toarray())
print(similarity[0][0])

0.8944271909999159


In [9]:
def gender_features(word):
    return {'last_letter': word[-1]}

In [10]:
gender_features('Kirti')

{'last_letter': 'i'}

In [11]:
from nltk.corpus import names

In [12]:
names.words()

['Abagael',
 'Abagail',
 'Abbe',
 'Abbey',
 'Abbi',
 'Abbie',
 'Abby',
 'Abigael',
 'Abigail',
 'Abigale',
 'Abra',
 'Acacia',
 'Ada',
 'Adah',
 'Adaline',
 'Adara',
 'Addie',
 'Addis',
 'Adel',
 'Adela',
 'Adelaide',
 'Adele',
 'Adelice',
 'Adelina',
 'Adelind',
 'Adeline',
 'Adella',
 'Adelle',
 'Adena',
 'Adey',
 'Adi',
 'Adiana',
 'Adina',
 'Adora',
 'Adore',
 'Adoree',
 'Adorne',
 'Adrea',
 'Adria',
 'Adriaens',
 'Adrian',
 'Adriana',
 'Adriane',
 'Adrianna',
 'Adrianne',
 'Adrien',
 'Adriena',
 'Adrienne',
 'Aeriel',
 'Aeriela',
 'Aeriell',
 'Ag',
 'Agace',
 'Agata',
 'Agatha',
 'Agathe',
 'Aggi',
 'Aggie',
 'Aggy',
 'Agna',
 'Agnella',
 'Agnes',
 'Agnese',
 'Agnesse',
 'Agneta',
 'Agnola',
 'Agretha',
 'Aida',
 'Aidan',
 'Aigneis',
 'Aila',
 'Aile',
 'Ailee',
 'Aileen',
 'Ailene',
 'Ailey',
 'Aili',
 'Ailina',
 'Ailyn',
 'Aime',
 'Aimee',
 'Aimil',
 'Aina',
 'Aindrea',
 'Ainslee',
 'Ainsley',
 'Ainslie',
 'Ajay',
 'Alaine',
 'Alameda',
 'Alana',
 'Alanah',
 'Alane',
 'Alanna',
 

In [13]:
print(len(names.words()))

7944


In [14]:
labeled_names = [(name, 'male') for name in names.words('male.txt')] + \
                [(name, 'female') for name in names.words('female.txt')]


In [15]:
import random
random.shuffle(labeled_names)

In [16]:
featuresets = [(gender_features(n), gender) for (n,gender) in labeled_names]

In [17]:
train_set, test_set = featuresets[5000:], featuresets[:2000]

In [18]:
import nltk 
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [19]:
classifier.classify(gender_features('David'))

'male'

In [20]:
print(nltk.classify.accuracy(classifier,test_set))

0.777


In [21]:
import nltk

In [22]:
f = open('/Users/aditya/Downloads/tweets1.txt','r')

In [23]:
text = f.read()
text1 = text.split()
text2 = nltk.Text(text1)

In [24]:
text2.concordance("find")

Displaying 9 of 9 matches:
or joy Main session is over. Time to find people I am sitting waitng for the s
beer baroness holds a competition to find the world's saddest music. Tonight, 
hose people who flies frequently can find the energy to work. XY Doc: "Secrets
 PTs State Conference in Roanoke VA. Find out more - url building out some wor
orld-class usability expertise. Must find out how. Watching lord of the rings 
nteresting guy...I like him. I can't find my hellyeahdude coaster? Installed F
em off to the printer! scrambling to find a buddy with wheels to pick up a mat
er opportunity at a Magnet Hospital? Find what you've been looking for at Rest
ll is well! Happy Wednesday 01.23.08 Find out where pro abort Catholic pols go


In [25]:
text2.concordance("people")

Displaying 4 of 4 matches:
 Main session is over. Time to find people I am sitting waitng for the session
g! I feel tired. I wonder how those people who flies frequently can find the e
be) quicksilver plus twitter Why do people exit and enter the lifts so slowly?
o slowly? Don't they know the other people in the lifts have better things to 


In [26]:
from urllib import request

In [27]:
url = "http://www.gutenberg.org/files/2554/2554-0.txt"

In [28]:
response = request.urlopen(url)

In [29]:
raw = response.read()

In [1]:
!rm -rf .git

In [2]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/aditya/.git/


In [3]:
!git add nltk.ipynb

In [4]:
!git commit -m "Initial commit: Added nltk.ipynb"

[master (root-commit) 87ad0ea] Initial commit: Added nltk.ipynb
 1 file changed, 1919 insertions(+)
 create mode 100644 nltk.ipynb


In [5]:
!git remote add origin https://github.com/Aditya-111-a/NLP--22MID0062-.git

In [7]:
!git remote set-url origin https://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@github.com/Aditya-111-a/NLP--22MID0062-.git

In [8]:
!git remote -v

origin	https://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@github.com/Aditya-111-a/NLP--22MID0062-.git (fetch)
origin	https://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@github.com/Aditya-111-a/NLP--22MID0062-.git (push)


In [9]:
!git branch -M main
!git push -u origin main

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 9.34 KiB | 9.34 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/Aditya-111-a/NLP--22MID0062-.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.


# Sentimental Analysis (IMDb Dataset)

In [2]:
import pandas as pd
df = pd.read_csv("/Users/aditya/Downloads/IMDB Dataset.csv")

In [12]:
df.head(10) # Reviewing first 10 rows and columns

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [13]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer() # initialise CountVectorizer
docs = np.array(['The Sun is shining',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

In [14]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [15]:
# Print the feature vector that is created 
print(bag.toarray()) # converting bag to array

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [16]:
# Count Vectoriser is like a TF Vectoriser